### ISSUE TITLE
Payment confirmation via callback url

### ISSUE THREAD

**Issue by IanWambai** [IanWambai/Chowder#5]
Checking the user's SMS inbox to confirm payment has it's drawbacks, and using the callback URL will be much more secure.

**Comment by IanWambai** [comment]
I'll put up a way to confirm your transactions by providing a callback URL, but for now make sure that the product id, for every transaction is unique.

**Comment by IanWambai** [comment]
Payment confirmation has now been added.

**Comment by IanWambai** [comment]
There's currently no easy way to add your own callback URL. Fixing this.

**Comment by shuBomb** [comment]
I am unable to generate payment confirm dialog, Is it depend on the callback url?

I need this

The system will push a USSD menu to the customer and prompt the customer to enter their BONGA PIN and any other validation information

**Comment by IanWambai** [comment]
I'm currently a bit tied up and will look at this tomorrow. I've reopened the issue for now.

**Comment by shuBomb** [comment]
Ok thanks for quick response.. :)

**Comment by IanWambai** [comment]
Hi please post more details about your issue, the steps you've taken, what you're trying and the response you're getting. I've tested it and everything works okay.

Code and/or screenshots will help.
