### ISSUE TITLE
Unable to open dialog for entering Boga PIN

### ISSUE THREAD

**Issue by shuBomb** [IanWambai/Chowder#8]
I have used this library and all is working fine except boga pin confirmation dialog.
I am unable to enter boga pin for confirm payment. 
Please check the screenshot 
![screenshot_2017-06-02-15-37-31-686_com toe chowder](https://cloud.githubusercontent.com/assets/6330208/26722677/96f27f7c-47ae-11e7-93e0-50ea0354f474.png)

After enter pay button, this screen will be open 

![screenshot_2017-06-02-15-37-39-691_com toe chowder](https://cloud.githubusercontent.com/assets/6330208/26722689/ac5da3dc-47ae-11e7-8cf1-ca294db93d07.png)

After click on Ok button, nothig will be happned.

Please suggest me what I can do for further process?

Thanks

**Comment by IanWambai** [comment]
I'm currently a bit tied up and will look at this tomorrow.

**Comment by IanWambai** [comment]
I've just tested this and it works okay. But here are some reasons why you might not see the pop up:

- The phone number you entered is not the phone number on the SIM of the device you're using (so the USSD pop up happens on another device).
- The phone number you entered isn't a Safaricom number (This should fail, I think).
- The you entered a wrong phone number (so the USSD pop up happens on another device).

**Comment by shuBomb** [comment]
I have just downloaded your code from github and change my bill number and passkey (Provided by LIPA safaricom).  Also I have shared screenshot above.
I have used this safaricom number  0718291085
Please let me know if any kind of data/screenshot you required ?

Thanks

**Comment by IanWambai** [comment]
Install the sample apk [here](https://github.com/IanWambai/Chowder/blob/master/sample/chowder_sample.apk?raw=true), and then enter an amount, and the phone number, then let me know if you're seeing the USSD push from Safaricom.

**Comment by shuBomb** [comment]
Ok but I would like to know that the sample apk which you shared is working properly? I hope the passkey and bill number you are using this apk is valid.
let me try and let you know the output.

**Comment by IanWambai** [comment]
Yup, the pay bill number and passkey used in the sample apk are all working.

**Comment by shuBomb** [comment]
It seems like its not working on my phone.. Every time when I clicked to pay button, it gives toast message "Something went wrong".
Please check the screenshot
![img-20170605-wa0014](https://cloud.githubusercontent.com/assets/6330208/26815333/6d23b1a4-4aa9-11e7-841f-1d82acd39a61.jpg)

**Comment by IanWambai** [comment]
Are you using the demo APK? Don't change anything, and if you have, post your code because the error you're getting means you're missing parameters.

**Comment by shuBomb** [comment]
Sorry for delay, It working fine, I have made a little bit mistake and its about misunderstanding in code section.
I have test in Safaricom mobile and its working fine..
Thanks for your awesome support..

**Comment by IanWambai** [comment]
Glad to help :-)
